// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqfIcbkPnSbGLxjSSfhFUj4qHUtu9asU',
    appId: '1:4179044129:web:1caa887d210abdb6770060',
    messagingSenderId: '4179044129',
    projectId: 'tele2app',
    authDomain: 'tele2app.firebaseapp.com',
    storageBucket: 'tele2app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu84av_Xg0xGHa2gk6j1zXbI9KFprYhWI',
    appId: '1:4179044129:android:3a011dd9bfc069d4770060',
    messagingSenderId: '4179044129',
    projectId: 'tele2app',
    storageBucket: 'tele2app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56_pu4hIrw00zrqM5EZc4ypye8cW1Sfs',
    appId: '1:4179044129:ios:834db61a8df3455a770060',
    messagingSenderId: '4179044129',
    projectId: 'tele2app',
    storageBucket: 'tele2app.appspot.com',
    iosClientId: '4179044129-2sicpo6dnnr8jst8f25g4qmug2uf1n23.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeAChoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA56_pu4hIrw00zrqM5EZc4ypye8cW1Sfs',
    appId: '1:4179044129:ios:834db61a8df3455a770060',
    messagingSenderId: '4179044129',
    projectId: 'tele2app',
    storageBucket: 'tele2app.appspot.com',
    iosClientId: '4179044129-2sicpo6dnnr8jst8f25g4qmug2uf1n23.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeAChoice',
  );
}
